=== PedroSaraivaPC/Data-Integration-ID-Project/PedroSaraiva_a2023146226_LucasGolobovante_a2023140728_P1/praticalWork/paises.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="lista">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pais" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="continente" type="xs:string"/>
	<xs:element name="img_bandeira" type="xs:string"/>
	<xs:element name="area" type="xs:string"/>
	<xs:element name="cidades_importantes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cidade" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="capital" type="xs:string"/>
	<xs:element name="cidade" type="xs:string"/>
	<xs:element name="habitantes" type="xs:string"/>
	<xs:element name="lingua" type="xs:string"/>
	<xs:element name="paises_fronteira">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pais_fronteira" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="habitantes_porKM" type="xs:string"/>
	<xs:element name="casos_covid" type="xs:string"/>
	<xs:element name="pais">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="capital"/>
				<xs:element ref="continente"/>
				<xs:element ref="img_bandeira"/>
				<xs:element ref="area"/>
				<xs:element ref="habitantes"/>
				<xs:element ref="habitantes_porKM"/>
				<xs:element ref="presidente"/>
				<xs:element ref="casos_covid"/>
				<xs:element ref="mortes_covid"/>
				<xs:element ref="moeda"/>
				<xs:element ref="hino"/>
				<xs:element ref="linguas"/>
				<xs:element ref="religioes"/>
				<xs:element ref="cidades_importantes"/>
				<xs:element ref="paises_fronteira"/>
			</xs:sequence>
			<xs:attribute name="nome" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="religioes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="religiao" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="mortes_covid" type="xs:string"/>
	<xs:element name="hino" type="xs:string"/>
	<xs:element name="moeda" type="xs:string"/>
	<xs:element name="pais_fronteira" type="xs:string"/>
	<xs:element name="linguas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lingua" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="presidente" type="xs:string"/>
	<xs:element name="religiao" type="xs:string"/>
</xs:schema>

=== PedroSaraivaPC/Data-Integration-ID-Project/PedroSaraiva_a2023146226_LucasGolobovante_a2023140728_P1/praticalWork/paises.xml
<?xml version="1.0" encoding="utf-8"?>
<lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="paises.xsd">
     <pais nome="Roménia">
          <capital>Bucareste</capital>
          <continente>Europa</continente>
          <img_bandeira>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/174.png</img_bandeira>
          <area>238391.0</area>
          <habitantes>19524000</habitantes>
          <habitantes_porKM>81</habitantes_porKM>
          <presidente>Klaus Iohannis</presidente>
          <casos_covid>958918</casos_covid>
          <mortes_covid>23674</mortes_covid>
          <moeda>Leu romeno</moeda>
          <hino>https://db-city.s3.amazonaws.com/anthem/174.mp3</hino>
          <linguas>
               <lingua>Língua romena</lingua>
          </linguas>
          <religioes>
               <religiao>Ortodoxo - 70 %</religiao>
               <religiao>Cristianismo - 6 %</religiao>
               <religiao>Protestantismo - 6 %</religiao>
          </religioes>
          <cidades_importantes>
               <cidade>Bucareste</cidade>
               <cidade>Iaşi</cidade>
               <cidade>Cluj-Napoca</cidade>
               <cidade>Timişoara</cidade>
               <cidade>Constança</cidade>
               <cidade>Craiova</cidade>
               <cidade>Galaţi</cidade>
               <cidade>Braşov</cidade>
               <cidade>Ploieşti</cidade>
               <cidade>Brăila</cidade>
               <cidade>Oradea</cidade>
               <cidade>Dobreşti</cidade>
               <cidade>Bacău</cidade>
               <cidade>Arad</cidade>
               <cidade>Piteşti</cidade>
               <cidade>Sibiu</cidade>
               <cidade>Târgu Mureş</cidade>
               <cidade>Baia Mare</cidade>
               <cidade>Buzău</cidade>
               <cidade>Botoşani</cidade>
          </cidades_importantes>
          <paises_fronteira>
               <pais_fronteira>Hungria</pais_fronteira>
               <pais_fronteira>Ucrânia</pais_fronteira>
               <pais_fronteira>Moldávia</pais_fronteira>
               <pais_fronteira>Bulgária</pais_fronteira>
               <pais_fronteira>Sérvia</pais_fronteira>
          </paises_fronteira>
     </pais>
     <pais nome="Portugal">
          <capital>Lisboa</capital>
          <continente>Europa</continente>
          <img_bandeira>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/170.png</img_bandeira>
          <area>92230.0</area>
          <habitantes>10287000</habitantes>
          <habitantes_porKM>111</habitantes_porKM>
          <presidente>Marcelo Rebelo de Sousa</presidente>
          <casos_covid>822314</casos_covid>
          <mortes_covid>16859</mortes_covid>
          <moeda>euro</moeda>
          <hino>https://db-city.s3.amazonaws.com/anthem/170.mp3</hino>
          <linguas>
               <lingua>Português</lingua>
               <lingua>Mirandese</lingua>
          </linguas>
          <religioes>
               <religiao>Cristianismo - 97 %</religiao>
               <religiao>Protestantismo - 1 %</religiao>
          </religioes>
          <cidades_importantes>
               <cidade>Lisboa</cidade>
               <cidade>Amadora</cidade>
               <cidade>Sintra</cidade>
               <cidade>Seixal</cidade>
               <cidade>Vila Nova de Gaia</cidade>
               <cidade>Gondomar</cidade>
               <cidade>Porto</cidade>
               <cidade>Guimarães</cidade>
               <cidade>Cascais</cidade>
               <cidade>Odivelas</cidade>
               <cidade>Loures</cidade>
               <cidade>Coimbra</cidade>
               <cidade>Braga</cidade>
               <cidade>Vila Franca de Xira</cidade>
               <cidade>Almada</cidade>
               <cidade>Santa Maria da Feira</cidade>
               <cidade>Matosinhos</cidade>
               <cidade>Maia</cidade>
               <cidade>Oeiras</cidade>
               <cidade>Vila Nova de Famalicão</cidade>
          </cidades_importantes>
          <paises_fronteira>
               <pais_fronteira>Espanha</pais_fronteira>
          </paises_fronteira>
     </pais>
     <pais nome="Brasil">
          <capital>Brasília</capital>
          <continente>América</continente>
          <img_bandeira>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/30.png</img_bandeira>
          <area>8510417.771</area>
          <habitantes>208325000</habitantes>
          <habitantes_porKM>24</habitantes_porKM>
          <presidente>Jair Bolsonaro</presidente>
          <casos_covid>12839844</casos_covid>
          <mortes_covid>325284</mortes_covid>
          <moeda>Real</moeda>
          <hino>https://db-city.s3.amazonaws.com/anthem/30.mp3</hino>
          <linguas>
               <lingua>Português</lingua>
          </linguas>
          <religioes>
               <religiao>Catolicismo - 80 %</religiao>
               <religiao>Outros - 20 %</religiao>
          </religioes>
          <cidades_importantes>
               <cidade>São Paulo</cidade>
               <cidade>Campinas</cidade>
               <cidade>Rio de Janeiro</cidade>
               <cidade>Manaus</cidade>
               <cidade>Belo Horizonte</cidade>
               <cidade>Belém</cidade>
               <cidade>Brasília</cidade>
               <cidade>Vitória</cidade>
               <cidade>Recife</cidade>
               <cidade>Baixada Santista</cidade>
               <cidade>Porto Alegre</cidade>
               <cidade>Fortaleza</cidade>
               <cidade>São Luís</cidade>
               <cidade>Curitiba</cidade>
               <cidade>Natal</cidade>
               <cidade>Salvador</cidade>
               <cidade>Maceió</cidade>
               <cidade>Goiânia</cidade>
               <cidade>Florianópolis</cidade>
          </cidades_importantes>
          <paises_fronteira>
               <pais_fronteira>Argentina</pais_fronteira>
               <pais_fronteira>Bolívia</pais_fronteira>
               <pais_fronteira>Colômbia</pais_fronteira>
               <pais_fronteira>Guiana Francesa</pais_fronteira>
               <pais_fronteira>França</pais_fronteira>
               <pais_fronteira>Guiana</pais_fronteira>
               <pais_fronteira>Paraguai</pais_fronteira>
               <pais_fronteira>Peru</pais_fronteira>
               <pais_fronteira>Suriname</pais_fronteira>
               <pais_fronteira>Uruguai</pais_fronteira>
               <pais_fronteira>Venezuela</pais_fronteira>
          </paises_fronteira>
     </pais>
     <pais nome="Paquistão">
          <capital>Islamabade</capital>
          <continente>Ásia</continente>
          <img_bandeira>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/160.png</img_bandeira>
          <area>880940.0</area>
          <habitantes>200960000</habitantes>
          <habitantes_porKM>228</habitantes_porKM>
          <presidente>Arif Alvi</presidente>
          <casos_covid>678165</casos_covid>
          <mortes_covid>14613</mortes_covid>
          <moeda>Rupia paquistanesa</moeda>
          <hino>https://db-city.s3.amazonaws.com/anthem/160.mp3</hino>
          <linguas>
               <lingua>Inglês</lingua>
               <lingua>Urdu</lingua>
          </linguas>
          <religioes>
               <religiao>Islão - 97 %</religiao>
               <religiao>Outros - 3 %</religiao>
          </religioes>
          <cidades_importantes>
               <cidade>Carachi</cidade>
               <cidade>Sargodha</cidade>
               <cidade>Laore</cidade>
               <cidade>Sialcote</cidade>
               <cidade>Faiçalabade</cidade>
               <cidade>Baaualpur</cidade>
               <cidade>Raualpindi</cidade>
               <cidade>Jhang</cidade>
               <cidade>Gujranwala</cidade>
               <cidade>Shekhupura</cidade>
               <cidade>Multan</cidade>
               <cidade>Gujrat</cidade>
               <cidade>Haiderabade</cidade>
               <cidade>Sucur</cidade>
               <cidade>Pexauar</cidade>
               <cidade>Larkana</cidade>
               <cidade>Quetta</cidade>
               <cidade>Sahiwal</cidade>
               <cidade>Islamabade</cidade>
               <cidade>Okara</cidade>
          </cidades_importantes>
          <paises_fronteira>
               <pais_fronteira>Índia</pais_fronteira>
               <pais_fronteira>Afeganistão</pais_fronteira>
               <pais_fronteira>Irão</pais_fronteira>
               <pais_fronteira>China</pais_fronteira>
          </paises_fronteira>
     </pais>
     <pais nome="Suíça">
          <capital>Berna</capital>
          <continente>Europa</continente>
          <img_bandeira>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/203.png</img_bandeira>
          <area>41285.0</area>
          <habitantes>8484000</habitantes>
          <habitantes_porKM>205</habitantes_porKM>
          <presidente>Simonetta Sommaruga</presidente>
          <casos_covid>603092</casos_covid>
          <mortes_covid>10350</mortes_covid>
          <moeda>Franco suíço</moeda>
          <hino>https://db-city.s3.amazonaws.com/anthem/203.mp3</hino>
          <linguas>
               <lingua>Língua alemã</lingua>
               <lingua>Francesa</lingua>
               <lingua>Italiano</lingua>
               <lingua>Reto-romano</lingua>
          </linguas>
          <religioes>
               <religiao>Cristianismo - 48 %</religiao>
               <religiao>Protestantismo - 45 %</religiao>
               <religiao>Outros - 8 %</religiao>
          </religioes>
          <cidades_importantes>
               <cidade>Zurique</cidade>
               <cidade>Genebra</cidade>
               <cidade>Basileia</cidade>
               <cidade>Berna</cidade>
               <cidade>Lausanne</cidade>
               <cidade>Winterthur</cidade>
               <cidade>Lucerna</cidade>
               <cidade>Lugano</cidade>
          </cidades_importantes>
          <paises_fronteira>
